apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  template:
    metadata:
      labels:
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: MONGO_DB_NAME
              value: app-desafio10
            - name: MONGO_DB_PASS
              value: s3cr3t!
            - name: MONGO_DB_URI
              value: mongodb://db-server:27017
            - name: MONGO_DB_USER
              value: root
            - name: PORT
              value: "3000"
          image: app
          name: educacionit-app
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
