apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio11-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desafio11-mongo
  template:
    metadata:
      labels:
        app: desafio11-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:7.0
        ports: 
        - containerPort: 2707
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "s3cr3t!"



