version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://ignacio:desafio10@mongo:27017/educacionit?authSource=admin
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ignacio
      MONGO_INITDB_ROOT_PASSWORD: desafio10
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

networks:
  app-network:
    driver: bridge


